

u1 = User.create(first_name: "Bryan", last_name: "Meadows", email: "bryan1993meadows@gmail.com", password: "password")
u2 = User.create(first_name: "John", last_name: "Doe", email: "john@email.com", password: "password",)

m1 = Product.create(name: "Black Long Sleeve", price: 12.00, description: "A black long sleeve gym shirt", image: "https://i.pinimg.com/736x/0e/a6/c3/0ea6c313c506fba279c517ad9963764b.jpg", stock: 5, gender: "male")
m2 = Product.create(name: "Blue Long Sleeve", price: 13.25, description: "High quality long sleeve gym shirt", image: "https://www.gymclothes.com/wp-content/uploads/2019/11/wholesale-seamless-dri-fit-full-sleeve-shirts-manufacturers.jpeg", stock: 10, gender: "male")
m3 = Product.create(name: "Grey Gym Pants", price: 12.25, description: "High quality gym pants", image: "https://i5.walmartimages.com/asr/47e03045-8fc0-400a-968f-0f2a3d18daab.1757dce5f7fbb164e2747cc6df0fc684.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", stock: 1, gender: "male")
m4 = Product.create(name: "Grey Joggers", price: 10.00, description: "High quality Joggers", image: "https://images.lululemon.com/is/image/lululemon/LM5AJLS_035956_1", stock: 10, gender: "male")
m5 = Product.create(name: "Grey Short Sleeve Gym Shirt", price: 9.00, description: "High quality short sleeve gym shirt", image: "https://www.hylete.com/media/catalog/product/cache/2855bb8175fcdcfec43ad0419f9911f0/h/y/hy_reflex_ss_m_pdp_sp22_1500x1500_gm_1.jpg", stock: 10, gender: "male")
m6 = Product.create(name: "Green Short Sleeve V-Neck", price: 10.00, description: "High quality short sleeve v-neck", image: "https://img.grouponcdn.com/stores/4Kyq2R3h7jZrz7VrVQCrV6LwSLHf/storesoi52504189-1333x800/v1/c870x524.jpg", stock: 10, gender: "male")
m7 = Product.create(name: "Grey Jogging Shorts", price: 10.00, description: "High quality Jogging Shorts", image: "https://i.ebayimg.com/images/g/2UUAAOSwLjtiO9Wa/s-l500.jpg", stock:10, gender: "male")
m8 = Product.create(name: "Red Gym Shorts", price: 12.00, description: "High quality gym shorts", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5knTiB4gk056iHLoIhO2lo9Ukbfe0SJpBhQ&usqp=CAU", stock:10, gender: "male")


w1 = Product.create(name: "Grey Long Sleeve", price:12.00, description: "High Quality Grey Long Sleeve Gym Shirt", image: "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1636046438-screen-shot-2021-11-04-at-1-04-02-pm-1636045452.png?crop=0.8646864686468647xw:1xh;center,top&resize=480:*", stock: 10, gender: "female")
w2 = Product.create(name: "Desert Long Sleeve", price:13.25, description: "High Quality Desert Long Sleeve Gym Shirt", image: "https://i.stpost.com/free-people-movement-called-it-layer-crop-shirt-back-zip-neck-long-sleeve-for-women-in-2224-desert-taupe-combo~p~1fhkt_02~440.2.jpg/", stock: 10, gender: "female")
w3 = Product.create(name: "Green Gym Pants", price: 12.25, description: "High Quality Green Gym Pants", image: "https://i5.walmartimages.com/asr/fc35c67e-8fcd-480d-bee3-55d57e03daab.91a55415a3d859d9300a9caa774ba224.jpeg", stock:10, gender: "female")
w4 = Product.create(name: "Tan Gym Pants with Pockets", price: 13.00, description:"High Quality Tan Gym Pants with Pockets", image: "https://sc04.alicdn.com/kf/H2a15d5a9b44e4f6ca8b032889950f203q/239716247/H2a15d5a9b44e4f6ca8b032889950f203q.jpg", stock:10, gender: "female")
w5 = Product.create(name: "Reddish Short Sleeve Gym Shirt", price: 10.00, description: "High Quality Reddish Short Sleeve Gym Shirt", image: "https://www.rei.com/media/b2c3e9ba-2c87-4c1c-bb2c-42112b7dd977.jpg", stock:10, gender: "female")
w6 = Product.create(name: "Mint Short Sleeve Gym Shirt", price: 10.00, description: "High Quality Mint Short Sleeve Gym Shirt", image: "https://i5.walmartimages.com/asr/3ce9bf9d-43a1-44a1-9652-10cda04110a9_1.95e6a9fdc074f730dcda7bcea1cf71a8.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF", stock:10, gender: "female")
w7 = Product.create(name: "Salmon Gym Shorts", price: 9.00, description:"High Quality Salmon Gym Shorts", image: "https://www.etonline.com/sites/default/files/images/2022-07/nike%20basketball%20shorts.JPG", stock:5, gender: "female")
w8 = Product.create(name: "Blue Gym Shorts", price: 9.00, description:"High Quality Blue Gym Shorts", image: "https://barbend.com/wp-content/uploads/2019/11/WomensBballshorts_ettel.jpg", stock:5, gender: "female")


s1 = Sizing.create(size: "Small", price: 0.00)
s2 = Sizing.create(size: "Medium", price: 0.25)
s3 = Sizing.create(size: "Large", price: 0.50)

ps1_1 = ProductSizing.create(product_id: m1.id, sizing_id: s1.id)
ps1_2 = ProductSizing.create(product_id: m1.id, sizing_id: s2.id)
ps1_3 = ProductSizing.create(product_id: m1.id, sizing_id: s3.id)
ps2_1 = ProductSizing.create(product_id: m2.id, sizing_id: s1.id)
ps2_2 = ProductSizing.create(product_id: m2.id, sizing_id: s2.id)
ps2_3 = ProductSizing.create(product_id: m2.id, sizing_id: s3.id)
ps3_1 = ProductSizing.create(product_id: m3.id, sizing_id: s1.id)
ps3_2 = ProductSizing.create(product_id: m3.id, sizing_id: s2.id)
ps3_3 = ProductSizing.create(product_id: m3.id, sizing_id: s3.id)
ps4_1 = ProductSizing.create(product_id: m4.id, sizing_id: s1.id)
ps4_2 = ProductSizing.create(product_id: m4.id, sizing_id: s2.id)
ps4_3 = ProductSizing.create(product_id: m4.id, sizing_id: s3.id)
ps5_1 = ProductSizing.create(product_id: m5.id, sizing_id: s1.id)
ps5_2 = ProductSizing.create(product_id: m5.id, sizing_id: s2.id)
ps5_3 = ProductSizing.create(product_id: m5.id, sizing_id: s3.id)
ps6_1 = ProductSizing.create(product_id: m6.id, sizing_id: s1.id)
ps6_2 = ProductSizing.create(product_id: m6.id, sizing_id: s2.id)
ps6_3 = ProductSizing.create(product_id: m6.id, sizing_id: s3.id)
ps7_1 = ProductSizing.create(product_id: m7.id, sizing_id: s1.id)
ps7_2 = ProductSizing.create(product_id: m7.id, sizing_id: s2.id)
ps7_3 = ProductSizing.create(product_id: m7.id, sizing_id: s3.id)
ps8_1 = ProductSizing.create(product_id: m8.id, sizing_id: s1.id)
ps8_2 = ProductSizing.create(product_id: m8.id, sizing_id: s2.id)
ps8_3 = ProductSizing.create(product_id: m8.id, sizing_id: s3.id)
ps9_1 = ProductSizing.create(product_id: w1.id, sizing_id: s1.id)
ps9_2 = ProductSizing.create(product_id: w1.id, sizing_id: s2.id)
ps9_3 = ProductSizing.create(product_id: w1.id, sizing_id: s3.id)
ps10_1 = ProductSizing.create(product_id: w2.id, sizing_id: s1.id)
ps10_2 = ProductSizing.create(product_id: w2.id, sizing_id: s2.id)
ps10_3 = ProductSizing.create(product_id: w2.id, sizing_id: s3.id)
ps11_1 = ProductSizing.create(product_id: w3.id, sizing_id: s1.id)
ps11_2 = ProductSizing.create(product_id: w3.id, sizing_id: s2.id)
ps11_3 = ProductSizing.create(product_id: w3.id, sizing_id: s3.id)
ps12_1 = ProductSizing.create(product_id: w4.id, sizing_id: s1.id)
ps12_2 = ProductSizing.create(product_id: w4.id, sizing_id: s2.id)
ps12_3 = ProductSizing.create(product_id: w4.id, sizing_id: s3.id)
ps13_1 = ProductSizing.create(product_id: w5.id, sizing_id: s1.id)
ps13_2 = ProductSizing.create(product_id: w5.id, sizing_id: s2.id)
ps13_3 = ProductSizing.create(product_id: w5.id, sizing_id: s3.id)
ps14_1 = ProductSizing.create(product_id: w6.id, sizing_id: s1.id)
ps14_2 = ProductSizing.create(product_id: w6.id, sizing_id: s2.id)
ps14_3 = ProductSizing.create(product_id: w6.id, sizing_id: s3.id)
ps15_1 = ProductSizing.create(product_id: w7.id, sizing_id: s1.id)
ps15_2 = ProductSizing.create(product_id: w7.id, sizing_id: s2.id)
ps15_3 = ProductSizing.create(product_id: w7.id, sizing_id: s3.id)
ps16_1 = ProductSizing.create(product_id: w8.id, sizing_id: s1.id)
ps16_2 = ProductSizing.create(product_id: w8.id, sizing_id: s2.id)
ps16_3 = ProductSizing.create(product_id: w8.id, sizing_id: s3.id)
